### ISSUE TITLE
Not starting on Ubuntu/Debian

### ISSUE THREAD

**Issue by mambucodev** [du-cki/comet#3]
I was trying to dockerize your repo, when I noticed that it gave me an error: https://paste.owlhosting.cloud/pufokugade.properties
I tried to install `openssl` and `libssl-dev` with `sudo apt-get install openssl libssl-dev -y` as it says but nothing changed.
also tried to change Env Variables but nothing changes again.
I tried it on a local linux machine too and nothing changed again, what's the issue?

**Comment by mambucodev** [comment]
I also have some basic knowledge of Rust so I tried to eventually read the code and try if there were any issues but still, nothing changed.

**Comment by Hadock-is-ok** [comment]
try installing pkg-config, looking online for the same error brings up a lot of SO answers installing that package.
see: https://stackoverflow.com/questions/65553557/why-rust-is-failing-to-build-command-for-openssl-sys-v0-9-60-even-after-local-in

**Comment by Hadock-is-ok** [comment]
@mambucodev did you ever fix the issue?

**Comment by mambucodev** [comment]
@Hadock-is-ok if you remember I texted you on discord and I told you I fixed it just by compiling the file on my machine and uploading it to docker. It's an issue that rust has while compiling OpenSSL, so it looks like it's not related to your package at all.

**Comment by mambucodev** [comment]
maybe trying updating packages, espacially openssl, would fix the issue. they probably fixed it during this whole time

**Comment by Hadock-is-ok** [comment]
> @Hadock-is-ok if you remember I texted you on discord and I told you I fixed it just by compiling the file on my machine and uploading it to docker. It's an issue that rust has while compiling OpenSSL, so it looks like it's not related to your package at all.

I actually don't, but I'm glad you got it fixed!
